services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html
    networks:
      - default
      - dev-cli_web
  nginx:
    image: nginx
    volumes:
      - ./conf/site.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/html
    depends_on:
      - php
    ports:
      - "8080:80"
    networks:
      - default
      - dev-cli_web
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}0.rule=Host(`${COMPOSE_PROJECT_NAME}.${TLD}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}0.middlewares=redirect-to-https

      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${TLD}`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true

networks:
  dev-cli_web:
    external: true
